version: "3.8"

services:
  web-ui:
    build: web_ui/.
    ports:
      - "8081:80"

  lob-java-demo:
    build: lob-java/.
    depends_on:
      - web-ui
    environment:
      PORT: 5555
      LOB_API_TEST_KEY: ${LOB_API_TEST_KEY}
      LOB_API_LIVE_KEY: ${LOB_API_LIVE_KEY}
    ports:
      - "5555:5555"

  lob-node-demo:
    build: lob-node/.
    depends_on:
      - web-ui
    environment:
      PORT: 5555
      LOB_API_TEST_KEY: ${LOB_API_TEST_KEY}
      LOB_API_LIVE_KEY: ${LOB_API_LIVE_KEY}
    ports:
      - "5555:5555"

  typescript-demo:
    build: typescript/.
    depends_on:
      - web-ui
    environment:
      PORT: 5555
      LOB_API_TEST_KEY: ${LOB_API_TEST_KEY}
      LOB_API_LIVE_KEY: ${LOB_API_LIVE_KEY}
    ports:
      - "5555:5555"
