version: '3.8'

services:
  ui:
    build: ui/.
    environment:
      PORT: 8080
    ports:
      - "8080:8080"

  typescript-demo:
    build: typescript/.
    depends_on:
      - ui
    environment:
      PORT: 5000
      LOB_API_KEY: <<REDACTED>>
    ports:
      - "5000:5000"
