version: "3.8"

services:
  web-ui:
    build: web_ui/.
    ports:
      - "8081:80"

  lob-node-demo:
    build: lob-node/.
    depends_on:
      - web-ui
    environment:
      PORT: 5000
      LOB_API_KEY: ${LOB_API_KEY}
      LOB_LIVE_API_KEY: ${LOB_LIVE_API_KEY}
    ports:
      - "5000:5000"

  typescript-demo:
    build: typescript/.
    depends_on:
      - web-ui
    environment:
      PORT: 5000
      LOB_API_KEY: ${LOB_API_KEY}
      LOB_LIVE_API_KEY: ${LOB_LIVE_API_KEY}
    ports:
      - "5000:5000"
