version: '3.8'

services:
  static-ui:
    build: static_ui/.
    ports:
      - "3117:80"

  typescript-demo:
    build: typescript/.
    depends_on:
      - static-ui
    environment:
      PORT: 5000
      LOB_API_KEY: <<REDACTED>>
    ports:
      - "5000:5000"

  java-demo:
    build: java/.
    depends_on:
      - ui
    environment:
      PORT: 5000
      LOB_API_KEY: <<REDACTED>>
    ports:
      - "5000:5000"
